//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SomerenUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SomerenUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stock empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong: .
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to select a drink. .
        /// </summary>
        internal static string ErrorMessageDrinkNotSelected {
            get {
                return ResourceManager.GetString("ErrorMessageDrinkNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to show..
        /// </summary>
        internal static string ErrorMessageNoDataToShow {
            get {
                return ResourceManager.GetString("ErrorMessageNoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to input a name. .
        /// </summary>
        internal static string ErrorMessageNoName {
            get {
                return ResourceManager.GetString("ErrorMessageNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to select a student..
        /// </summary>
        internal static string ErrorMessageStudentNotSelected {
            get {
                return ResourceManager.GetString("ErrorMessageStudentNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input for price. Needs to be a number..
        /// </summary>
        internal static string ErrorMessageWrongPrice {
            get {
                return ResourceManager.GetString("ErrorMessageWrongPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input for quantity. Needs to be a whole number..
        /// </summary>
        internal static string ErrorMessageWrongQuantityFormat {
            get {
                return ResourceManager.GetString("ErrorMessageWrongQuantityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input for stock. Needs to be a number..
        /// </summary>
        internal static string ErrorMessageWrongStock {
            get {
                return ResourceManager.GetString("ErrorMessageWrongStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        internal static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        internal static string MoneyFormat {
            get {
                return ResourceManager.GetString("MoneyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stock nearly depleted.
        /// </summary>
        internal static string NearlyDepleted {
            get {
                return ResourceManager.GetString("NearlyDepleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New purchase..
        /// </summary>
        internal static string NewPurchase {
            get {
                return ResourceManager.GetString("NewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnl.
        /// </summary>
        internal static string PanelName {
            get {
                return ResourceManager.GetString("PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap someren {
            get {
                object obj = ResourceManager.GetObject("someren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to someren.Image.
        /// </summary>
        internal static string SomerenImage {
            get {
                return ResourceManager.GetString("SomerenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added: .
        /// </summary>
        internal static string SuccessfullyAdded {
            get {
                return ResourceManager.GetString("SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted: .
        /// </summary>
        internal static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully edited: .
        /// </summary>
        internal static string SuccessfullyEdited {
            get {
                return ResourceManager.GetString("SuccessfullyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stock sufficient.
        /// </summary>
        internal static string Sufficient {
            get {
                return ResourceManager.GetString("Sufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
